// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429085644_InitialRealCreate")]
    partial class InitialRealCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Model.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CostPrice")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CostPrice = 85.0,
                            IsAlcoholic = true,
                            Name = "Sex on the beach"
                        },
                        new
                        {
                            Id = 11,
                            CostPrice = 95.0,
                            IsAlcoholic = true,
                            Name = "Long Island Iced Tea"
                        },
                        new
                        {
                            Id = 60,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Astronaut"
                        },
                        new
                        {
                            Id = 61,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Basic Bitch"
                        },
                        new
                        {
                            Id = 62,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Brandbil"
                        },
                        new
                        {
                            Id = 63,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Champagnebrus"
                        },
                        new
                        {
                            Id = 64,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Purple Rain"
                        },
                        new
                        {
                            Id = 65,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Dumle"
                        },
                        new
                        {
                            Id = 66,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Filur"
                        },
                        new
                        {
                            Id = 67,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Flagermus"
                        },
                        new
                        {
                            Id = 68,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Gin Hass"
                        },
                        new
                        {
                            Id = 69,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Skumbanan"
                        },
                        new
                        {
                            Id = 70,
                            CostPrice = 20.0,
                            IsAlcoholic = true,
                            Name = "Southern & Sprite"
                        },
                        new
                        {
                            Id = 90,
                            CostPrice = 20.0,
                            IsAlcoholic = false,
                            Name = "Børnebrandbil"
                        },
                        new
                        {
                            Id = 91,
                            CostPrice = 20.0,
                            IsAlcoholic = false,
                            Name = "Børnechampagnebrus"
                        },
                        new
                        {
                            Id = 92,
                            CostPrice = 20.0,
                            IsAlcoholic = false,
                            Name = "Børnefilur"
                        },
                        new
                        {
                            Id = 93,
                            CostPrice = 20.0,
                            IsAlcoholic = false,
                            Name = "Børneastronaut"
                        },
                        new
                        {
                            Id = 94,
                            CostPrice = 20.0,
                            IsAlcoholic = false,
                            Name = "Safe Sex On The Beach"
                        });
                });

            modelBuilder.Entity("Data.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("MaxStockQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinStockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Data.Model.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaleId"));

                    b.Property<int?>("DrinkId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtSale")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("SaleId");

                    b.HasIndex("DrinkId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "1234",
                            Role = 1,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "1234",
                            Role = 0,
                            UserName = "bar"
                        });
                });

            modelBuilder.Entity("DrinkLiquid", b =>
                {
                    b.Property<int>("DrinkId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("integer");

                    b.HasKey("DrinkId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("DrinkLiquid", (string)null);
                });

            modelBuilder.Entity("Data.Model.Consumables", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Consumables");
                });

            modelBuilder.Entity("Data.Model.Liquid", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.Property<double>("AlcoholPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Pant")
                        .HasColumnType("integer");

                    b.Property<bool>("SugarFree")
                        .HasColumnType("boolean");

                    b.Property<int>("VolumeCl")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Liquid");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CostPrice = 5.50m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Ceres Top",
                            StockQuantity = 100,
                            AlcoholPercentage = 4.5999999999999996,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 33
                        },
                        new
                        {
                            Id = 4,
                            CostPrice = 6.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Albani øl",
                            StockQuantity = 150,
                            AlcoholPercentage = 4.5999999999999996,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 33
                        },
                        new
                        {
                            Id = 5,
                            CostPrice = 12.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Shaker Sport",
                            StockQuantity = 80,
                            AlcoholPercentage = 4.5,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 33
                        },
                        new
                        {
                            Id = 20,
                            CostPrice = 150.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Vodka",
                            StockQuantity = 10,
                            AlcoholPercentage = 37.5,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 27,
                            CostPrice = 120.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Peach Schnapps",
                            StockQuantity = 5,
                            AlcoholPercentage = 18.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 25,
                            CostPrice = 15.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Appelsinjuice",
                            StockQuantity = 20,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 100
                        },
                        new
                        {
                            Id = 26,
                            CostPrice = 18.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Tranebærjuice",
                            StockQuantity = 20,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 100
                        },
                        new
                        {
                            Id = 80,
                            CostPrice = 40.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Grenadine",
                            StockQuantity = 15,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 50
                        },
                        new
                        {
                            Id = 81,
                            CostPrice = 15.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Saftevand (Rød)",
                            StockQuantity = 50,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 100
                        },
                        new
                        {
                            Id = 82,
                            CostPrice = 18.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Ananasjuice",
                            StockQuantity = 20,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 100
                        },
                        new
                        {
                            Id = 41,
                            CostPrice = 130.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Råstoff Strawberry/Rhubarb",
                            StockQuantity = 10,
                            AlcoholPercentage = 16.399999999999999,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 42,
                            CostPrice = 155.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Jägermeister",
                            StockQuantity = 5,
                            AlcoholPercentage = 35.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 43,
                            CostPrice = 125.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Cuba Caramel",
                            StockQuantity = 8,
                            AlcoholPercentage = 30.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 44,
                            CostPrice = 125.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Cuba Kurant",
                            StockQuantity = 8,
                            AlcoholPercentage = 30.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 45,
                            CostPrice = 130.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Råstoff Liquorice",
                            StockQuantity = 10,
                            AlcoholPercentage = 16.399999999999999,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 46,
                            CostPrice = 165.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Southern Comfort",
                            StockQuantity = 4,
                            AlcoholPercentage = 35.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 47,
                            CostPrice = 135.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Pisang Ambon",
                            StockQuantity = 6,
                            AlcoholPercentage = 20.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 48,
                            CostPrice = 10.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Red Soda",
                            StockQuantity = 100,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 33
                        },
                        new
                        {
                            Id = 49,
                            CostPrice = 10.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Green Soda",
                            StockQuantity = 100,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 33
                        },
                        new
                        {
                            Id = 55,
                            CostPrice = 10.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Orange Soda",
                            StockQuantity = 100,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 33
                        },
                        new
                        {
                            Id = 56,
                            CostPrice = 12.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Chocolate Milk",
                            StockQuantity = 40,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 100
                        },
                        new
                        {
                            Id = 57,
                            CostPrice = 25.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Lime Juice",
                            StockQuantity = 15,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 50
                        },
                        new
                        {
                            Id = 30,
                            CostPrice = 140.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Gin",
                            StockQuantity = 8,
                            AlcoholPercentage = 37.5,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 31,
                            CostPrice = 145.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Pink Gin",
                            StockQuantity = 5,
                            AlcoholPercentage = 37.5,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 36,
                            CostPrice = 45.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Mango Syrup",
                            StockQuantity = 10,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 70
                        },
                        new
                        {
                            Id = 38,
                            CostPrice = 10.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Lemon Soda",
                            StockQuantity = 100,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 33
                        },
                        new
                        {
                            Id = 39,
                            CostPrice = 10.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Faxe Kondi",
                            StockQuantity = 100,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 33
                        },
                        new
                        {
                            Id = 40,
                            CostPrice = 10.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Tonic Water",
                            StockQuantity = 100,
                            AlcoholPercentage = 0.0,
                            Pant = 0,
                            SugarFree = false,
                            VolumeCl = 33
                        });
                });

            modelBuilder.Entity("Data.Model.Snack", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.HasDiscriminator().HasValue("Snack");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            CostPrice = 10.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Popcorn",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 7,
                            CostPrice = 15.00m,
                            MaxStockQuantity = 0,
                            MinStockQuantity = 0,
                            Name = "Chips",
                            StockQuantity = 40
                        });
                });

            modelBuilder.Entity("Data.Model.Sale", b =>
                {
                    b.HasOne("Data.Model.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId");

                    b.HasOne("Data.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Drink");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DrinkLiquid", b =>
                {
                    b.HasOne("Data.Model.Drink", null)
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Model.Liquid", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
