// <auto-generated />
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416092913_KevinDevDrinkModel")]
    partial class KevinDevDrinkModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("MaxStockQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinStockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "1234",
                            Role = 1,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "1234",
                            Role = 0,
                            UserName = "bar"
                        });
                });

            modelBuilder.Entity("Data.Model.Consumables", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Consumables");
                });

            modelBuilder.Entity("Data.Model.LiquidWithAlcohol", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.Property<double>("AlcoholPercentage")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Pant")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalesPrice")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric");

                    b.Property<int>("VolumeCl")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("LiquidWithAlcohol");
                });

            modelBuilder.Entity("Data.Model.LiquidWithoutAlcohol", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.Property<decimal>("Pant")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalesPrice")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric");

                    b.Property<bool>("SugarFree")
                        .HasColumnType("boolean");

                    b.Property<int>("VolumeCl")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("LiquidWithoutAlcohol");
                });

            modelBuilder.Entity("Data.Model.Snack", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("numeric");

                    b.ToTable("Products", t =>
                        {
                            t.Property("SalesPrice")
                                .HasColumnName("Snack_SalesPrice");
                        });

                    b.HasDiscriminator().HasValue("Snack");
                });
#pragma warning restore 612, 618
        }
    }
}
