// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420083541_KevinDevPantToEnum")]
    partial class KevinDevPantToEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Model.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CostPrice")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SalesPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("Data.Model.DrinkIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DrinkId")
                        .HasColumnType("integer");

                    b.Property<int>("LiquidProductId")
                        .HasColumnType("integer");

                    b.Property<int>("VolumeCl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("LiquidProductId");

                    b.ToTable("DrinkIngredients");
                });

            modelBuilder.Entity("Data.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("MaxStockQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinStockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Data.Model.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaleId"));

                    b.Property<decimal>("PriceAtSale")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("SaleId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "1234",
                            Role = 1,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "1234",
                            Role = 0,
                            UserName = "bar"
                        });
                });

            modelBuilder.Entity("Data.Model.Consumables", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Consumables");
                });

            modelBuilder.Entity("Data.Model.LiquidProduct", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.Property<int>("Pant")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("VolumeCl")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("LiquidProduct");
                });

            modelBuilder.Entity("Data.Model.Snack", b =>
                {
                    b.HasBaseType("Data.Model.Product");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("numeric");

                    b.ToTable("Products", t =>
                        {
                            t.Property("SalesPrice")
                                .HasColumnName("Snack_SalesPrice");
                        });

                    b.HasDiscriminator().HasValue("Snack");
                });

            modelBuilder.Entity("Data.Model.LiquidWithAlcohol", b =>
                {
                    b.HasBaseType("Data.Model.LiquidProduct");

                    b.Property<double>("AlcoholPercentage")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("LiquidWithAlcohol");
                });

            modelBuilder.Entity("Data.Model.LiquidWithoutAlcohol", b =>
                {
                    b.HasBaseType("Data.Model.LiquidProduct");

                    b.Property<bool>("SugarFree")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("LiquidWithoutAlcohol");
                });

            modelBuilder.Entity("Data.Model.DrinkIngredient", b =>
                {
                    b.HasOne("Data.Model.Drink", "Drink")
                        .WithMany("Ingredients")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Model.LiquidProduct", "LiquidProduct")
                        .WithMany()
                        .HasForeignKey("LiquidProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("LiquidProduct");
                });

            modelBuilder.Entity("Data.Model.Sale", b =>
                {
                    b.HasOne("Data.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Data.Model.Drink", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
